apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: tsermakov/actium-ai-backend
  newName: tsermakov/actium-ai-backend
  newTag: 6f95840fefb31263ed15f9a015a03dd9d50dd799
- name: tsermakov/actium-templater-frontend
  newName: tsermakov/actium-templater-frontend
  newTag: 6f95840fefb31263ed15f9a015a03dd9d50dd799
- name: tsermakov/actium-user-account-backend
  newName: tsermakov/actium-user-account-backend
  newTag: 6f95840fefb31263ed15f9a015a03dd9d50dd799
