apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: tsermakov/actium-ai-backend
  newName: tsermakov/actium-ai-backend
  newTag: 981a0163d5aa2ca1803f74e91f56d4a89b85b803
- name: tsermakov/actium-templater-frontend
  newName: tsermakov/actium-templater-frontend
  newTag: 981a0163d5aa2ca1803f74e91f56d4a89b85b803
- name: tsermakov/actium-user-account-backend
  newName: tsermakov/actium-user-account-backend
  newTag: 981a0163d5aa2ca1803f74e91f56d4a89b85b803
