apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: tsermakov/actium-ai-backend
  newName: tsermakov/actium-ai-backend
  newTag: 2567a43802f9b69032c43ea5e4cb59b94e8b1d2d
- name: tsermakov/actium-templater-frontend
  newName: tsermakov/actium-templater-frontend
  newTag: 2567a43802f9b69032c43ea5e4cb59b94e8b1d2d
- name: tsermakov/actium-user-account-backend
  newName: tsermakov/actium-user-account-backend
  newTag: 2567a43802f9b69032c43ea5e4cb59b94e8b1d2d
