services:
  db:
    image: postgres:16
    container_name: docflow_db
    restart: always
    env_file: .env.local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net

  user-account:
    build:
      context: ./user-account
    image: mgfallen/docflow-go:latest
    container_name: docflow_go_backend
    restart: on-failure
    env_file: .env.local
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_net
      - frontend_net

  templater-api:
    build:
      context: ./templater/apps/api
    image: mgfallen/docflow-python:latest
    container_name: docflow_python_api
    env_file: .env.local
    networks:
      - backend_net
      - frontend_net

  frontend:
    build:
      context: ./templater/apps/web
    image: mgfallen/docflow-frontend:latest
    container_name: docflow_frontend
    env_file: .env.local
    ports:
      - "${FRONTEND_PORT}:5173"
    networks:
      - frontend_net
    depends_on:
      - templater-api
      - user-account

volumes:
  db_data:

networks:
  # front
  frontend_net:
    driver: bridge
    name: docflow_frontend_tier

  # back + BD
  backend_net:
    driver: bridge
    name: docflow_backend_tier
    internal: true