apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-account-srv
  namespace: actium-backend
spec:
  template:
    spec:
      initContainers:
        - name: db-migrate
          imagePullPolicy: IfNotPresent
      containers:
        - name: backend
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-srv
  namespace: actium-backend
spec:
  template:
    spec:
      containers:
        - name: ai-api
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: actium-frontend
spec:
  template:
    spec:
      containers:
        - name: web
          imagePullPolicy: IfNotPresent
