apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: tsermakov/actium-user-account-srv
    newName: tsermakov/actium-user-account-srv
    newTag: v1.1.0
  - name: tsermakov/actium-ai-srv
    newName: tsermakov/actium-ai-srv
    newTag: v1.0.0
  - name: tsermakov/actium-templater-frontend
    newName: tsermakov/actium-templater-frontend
    newTag: v1.2.0

patches:
  - path: image-pull-policy.yaml
