apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: actium-monitoring
  labels:
    app: grafana
    component: monitoring
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.actium-monitoring.svc.cluster.local:9090
        isDefault: true
        editable: true
  provider.yaml: |-
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /tmp/dashboards
