apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - backend-secret.yaml
  - network-policies.yaml
  - user-backend.yaml
  - ai-backend.yaml
  - frontend.yaml
  - migration-job.yaml
  - prometheus.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - grafana-provisioning.yaml
  - grafana-dashboard-user-backend.yaml
  - grafana-dashboard-frontend.yaml
  - grafana-dashboard-k8s-pods.yaml
  - grafana-dashboard-api-overview.yaml
  - grafana.yaml
  - ingress-backend.yaml
  - ingress-grafana.yaml
  - ingress-frontend.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: actium
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
