apiVersion: v1
kind: Namespace
metadata:
  name: actium-backend
  labels:
    app.kubernetes.io/name: actium
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: actium-frontend
  labels:
    app.kubernetes.io/name: actium
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: actium-monitoring
  labels:
    app.kubernetes.io/name: actium
    app.kubernetes.io/component: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: actium-database
  labels:
    app.kubernetes.io/name: actium
    app.kubernetes.io/component: database
