apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/timermakov/Actium.git
    targetRevision: master
    path: infra/k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: actium-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
